# Generated by Django 3.2.5 on 2021-08-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Totext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image',
            field=models.ImageField(default=None, upload_to='image'),
        ),
    ]
