# Generated by Django 3.2.5 on 2021-08-03 19:05

import Totext.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Totext', '0002_alter_imageuploadmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image',
            field=models.ImageField(default=None, upload_to=Totext.models.get_file_path),
        ),
    ]
